        #include <meta2.h>
        void run() {
        ADR(PROGRAM);
OUT1
        :;
        TST("*1");
        BF(L0);
        CL("GN1();");
        OUT();
L0
        :;
        BT(L1);
        TST("*2");
        BF(L2);
        CL("GN2();");
        OUT();
L2
        :;
        BT(L1);
        TST("*");
        BF(L3);
        CL("CI();");
        OUT();
L3
        :;
        BT(L1);
        SR();
        BF(L4);
        CL("CL(");
        CI();
        CL(");");
        OUT();
L4
        :;
L1
        :;
        R();
OUTPUT
        :;
        TST(".OUT");
        BF(L5);
        TST("(");
        BE();
L6
        :;
        CLL(OUT1,___L7);
        BT(L6);
        SET();
        BE();
        TST(")");
        BE();
L5
        :;
        BT(L8);
        TST(".LABEL");
        BF(L9);
        CL("LB();");
        OUT();
        CLL(OUT1,___L10);
        BE();
L9
        :;
L8
        :;
        BF(L11);
        CL("OUT();");
        OUT();
L11
        :;
L12
        :;
        R();
EX3
        :;
        ID();
        BF(L13);
        CL("CLL(");
        CI();
        CL(",___");
        GN1();
        CL(");");
        OUT();
L13
        :;
        BT(L14);
        SR();
        BF(L15);
        CL("TST(");
        CI();
        CL(");");
        OUT();
L15
        :;
        BT(L14);
        TST(".ID");
        BF(L16);
        CL("ID();");
        OUT();
L16
        :;
        BT(L14);
        TST(".NUMBER");
        BF(L17);
        CL("NUM();");
        OUT();
L17
        :;
        BT(L14);
        TST(".STRING");
        BF(L18);
        CL("SR();");
        OUT();
L18
        :;
        BT(L14);
        TST("(");
        BF(L19);
        CLL(EX1,___L20);
        BE();
        TST(")");
        BE();
L19
        :;
        BT(L14);
        TST(".EMPTY");
        BF(L21);
        CL("SET");
        OUT();
L21
        :;
        BT(L14);
        TST("$");
        BF(L22);
        LB();
        GN1();
        OUT();
        CL(":;");
        OUT();
        CLL(EX3,___L23);
        BE();
        CL("BT(");
        GN1();
        CL(");");
        OUT();
        CL("SET();");
        OUT();
L22
        :;
L14
        :;
        R();
EX2
        :;
        CLL(EX3,___L24);
        BF(L25);
        CL("BF(");
        GN1();
        CL(");");
        OUT();
L25
        :;
        BT(L26);
        CLL(OUTPUT,___L27);
        BF(L28);
L28
        :;
L26
        :;
        BF(L29);
L30
        :;
        CLL(EX3,___L31);
        BF(L32);
        CL("BE();");
        OUT();
L32
        :;
        BT(L33);
        CLL(OUTPUT,___L34);
        BF(L35);
L35
        :;
L33
        :;
        BT(L30);
        SET();
        BE();
        LB();
        GN1();
        OUT();
        CL(":;");
        OUT();
L29
        :;
L36
        :;
        R();
EX1
        :;
        CLL(EX2,___L37);
        BF(L38);
L39
        :;
        TST("/");
        BF(L40);
        CL("BT(");
        GN1();
        CL(");");
        OUT();
        CLL(EX2,___L41);
        BE();
L40
        :;
L42
        :;
        BT(L39);
        SET();
        BE();
        LB();
        GN1();
        OUT();
        CL(":;");
        OUT();
L38
        :;
L43
        :;
        R();
ST
        :;
        ID();
        BF(L44);
        LB();
        CI();
        OUT();
        CL(":;");
        OUT();
        TST("=");
        BE();
        CLL(EX1,___L45);
        BE();
        TST(".,");
        BE();
        CL("R();");
        OUT();
L44
        :;
L46
        :;
        R();
PROGRAM
        :;
        TST(".SYNTAX");
        BF(L47);
        ID();
        BE();
        CL("#include <meta2.h>");
        OUT();
        CL("void run() {");
        OUT();
        CL("ADR(");
        CI();
        CL(");");
        OUT();
L48
        :;
        CLL(ST,___L49);
        BT(L48);
        SET();
        BE();
        TST(".END");
        BE();
        CL("}");
        OUT();
L47
        :;
L50
        :;
        R();
        }
