#!/bin/sh

set -e

usage () 
{
    echo "usage: meta2c [OPTION ...] FILENAME [-o OUTFILE]"
    exit 1
}

infile=
outfile=a.out
options=

while test -n "$1"; do
    case "$1" in
        -h|-help|--help) 
	    usage;;
	-*v*|-*g*)
	    exec meta2 "$1";;
	-o) 
	    shift
	    outfile="$1"
	    shift;;
    	-*) 
	    options="$options $1"
	    shift;;
	*) 
	    if test -n "$infile"; then
		usage;
	    fi
	    infile="$1"
	    shift;;
    esac
done

test -n "$infile" || usage

case "$outfile" in
    *.c)
	tempc=$(mktemp XXXXXXXX.c)
	meta2 $options <"$infile" >$tempc
    *) 
	tempc=$(mktemp XXXXXXXX.c)
	meta2 $options <"$infile" >$tempc
	gcc -I. -O2 $tempc -o "$outfile"
	rm -f $tempc;;
esac
