#!/bin/bash
# usage: bash scripts/generate-version [GENERATOR [TARGETFILE]]
#
# generate self-contained and versioned bootstrap sources

generator=bootstrap/meta2
target=bootstrap/meta2.c

if test -n "$1"; then
    generator="$1"
fi

if test -n "$2"; then
    target="$2"
fi

# obtain HEAD id
fingerprint=$(git rev-parse HEAD)

# generate bootstrap source
echo '#define FINGERPRINT "'$fingerprint'"' >"$target"
echo '#define GENEALOGY \' >>"$target"

for v in $($generator -g); do
    echo '"'$v'\n" \' >>"$target"
done

parent=$($generator -v)
echo '"'$parent'\n"' >>"$target"
cat meta2.h meta2.c >>"$target"
