#!/bin/bash
#
# usage: bash scripts/regenerate [COMMIT]

set -e

# check for changes
if git diff --quiet; then :
else
    if test "$1" \!= "-n"; then
	echo "There are still uncommited changes in the working directory."
	echo "Please commit them first before restoring."
	exit 1
    fi
fi

target="$1"

if test -z "$target"; then
    target=$(shell bootstrap/meta2 -v)
fi

# copy scripts directory so that checking out the tree does not
# interfere with script-execution
rm -fr scripts.tmp
cp -r scripts scripts.tmp

exec bash scripts.tmp/regenerate-2 "$target"
