#!/bin/bash
#
# usage: bash scripts.tmp/restore-2 COMMIT
#
# This script should not be called directly - see scripts/restore

set -e

if test -z "$1"; then
    echo "usage: scripts.tmp/restore-2 COMMIT"
    exit 1
fi

# get HEAD commit
current=$(git rev-parse HEAD)

echo "initial HEAD is: " $current

git reset --hard "$1"
make -f Makefile bootstrap
touch meta2.meta2
make -f Makefile all

# restore HEAD
git reset --hard $current
