#!/bin/bash
#
# usage: bash scripts/restore COMMIT

set -e

# check for changes
if git diff --quiet; then :
else
    if test "$1" \!= "-n"; then
	echo "There are still uncommited changes in the working directory."
	echo "Please commit them first before restoring."
	exit 1
    fi
fi

if test -z "$1"; then
    echo "usage: bash scripts/restore COMMIT"
    exit 1
fi

# copy scripts directory so that checking out the tree does not
# interfere with script-execution
rm -fr scripts.tmp
cp -r scripts scripts.tmp

exec scripts.tmp/restore-2 "$1"
