#!/bin/bash
# usage: bash scripts/snapshot [-n] 
#
# generate reproducible snapshot

set -e

# check for changes
if git diff --quiet; then :
else
    if test "$1" \!= "-n"; then
	echo "There are still uncommited changes in the working directory."
	echo "Please commit them first before generating a snapshot."
	exit 1
    fi
fi

# force rebuild
touch meta2.meta2
make -f Makefile all check

# create bootstrap sources
bash scripts/generate-version

# obtain HEAD id
fingerprint=$(git rev-parse HEAD)

# regenerate meta2.c
make -f Makefile bootstrap

# commit bootstrap source
if test "$1" \!= "-n"; then
    echo "committing snapshot"
    git commit -m "snapshot" bootstrap/meta2.c
fi
